name: qit
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ">=2.17.0-182.2.beta <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  badges: ^2.0.2
  equatable: ^2.0.3
  fluro: ^2.0.3
  dio: ^4.0.6
  pretty_dio_logger: ^1.2.0-beta-1
  get_it: ^7.2.0
  rxdart: ^0.27.3
  bloc: ^6.1.3
  json_annotation: ^4.4.0
  shared_preferences: ^2.0.13
  dartz: ^0.10.1
  data_connection_checker: ^0.3.4
  flutter_bloc: ^6.1.1
  cool_alert: ^1.1.0
  flutter_riverpod: ^1.0.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.0.2
  freezed_annotation: ^2.0.1
  json_serializable: ^6.1.6
  build_runner: ^2.1.10
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Light.ttf

